name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.17-30
api-version: "1.13"
website: rypofalem.github.io
author: Wolfstorm
authors: [Wolfstorm, Marfjeh, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone]
description: Allows players to edit data of armorstands without any commands.
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permission: asedit.basic
permissions:
    asedit.basic:
      description: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: true
    asedit.invisible:
      description: Toggles ArmorStand and ItemFrame visibility.
      default: true
    asedit.rename:
      description: Rename armorstands
      default: true
    asedit.equipment:
      description: Access armorstand equipment GUI
      default: true
#   NOT CURRENTLY IN USE! Coming in a future update
#    asedit.reload:
#      description: Reload Configs for ArmorStandEditor
#      default: false