name: Nightly ASE Build of Main (CI/CD)

on:
  schedule:
  - cron: "0 23 * * *"

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: ['21']
        
    steps:
      - name: Checkout ArmorStandEditor
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
           java-version: ${{ matrix.java_version }}
           distribution: 'zulu'
           
      - name: Cache SonarCloud for Analysis
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache the Maven Packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2           

      - name: Build and analyze via Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=wolfieheart_ArmorStandEditor

      - name: Clean Verify
        run: mvn -B clean verify
        
      - name: Upload Artifact for Debugging
        uses: actions/upload-artifact@v4.3.3
        with:
          name: artifact
          path: /home/runner/work/ArmorStandEditor/ArmorStandEditor/target/armorstandeditor-*-*.jar
          if-no-files-found: error
          retention-days: 1
          overwrite: true

     
